Update odoo-tests.yml

diff --git a/.github/workflows/odoo-tests.yml b/.github/workflows/odoo-tests.yml
--- a/.github/workflows/odoo-tests.yml
+++ b/.github/workflows/odoo-tests.yml
@@ -40,25 +40,25 @@ jobs:
             build-essential python3-dev libldap2-dev \
             libsasl2-dev libssl-dev postgresql-client
 
-      - name: Wait for Postgres to be ready
-        run: |
-          for i in {1..60}; do  # Intentaremos 60 veces (1 minuto de espera total)
-            if pg_isready -h $DB_HOST -p $DB_PORT -U $DB_USER > /dev/null 2>&1; then
-              echo "Postgres is up"
-              exit 0
-            else
-              echo "Attempt $i: PostgreSQL is not ready yet"
-            fi
-            sleep 1
-          done
-          echo "Postgres did not become ready in time" >&2
-          exit 1
+      # - name: Wait for Postgres to be ready
+      #   run: |
+      #     for i in {1..60}; do  # Intentaremos 60 veces (1 minuto de espera total)
+      #       if pg_isready -h $DB_HOST -p $DB_PORT -U $DB_USER > /dev/null 2>&1; then
+      #         echo "Postgres is up"
+      #         exit 0
+      #       else
+      #         echo "Attempt $i: PostgreSQL is not ready yet"
+      #       fi
+      #       sleep 1
+      #     done
+      #     echo "Postgres did not become ready in time" >&2
+      #     exit 1
 
-      - name: Print PostgreSQL logs
-        if: failure()
-        run: |
-          docker ps
-          docker logs $(docker ps -q --filter "ancestor=postgres:13")
+      # - name: Print PostgreSQL logs
+      #   if: failure()
+      #   run: |
+      #     docker ps
+      #     docker logs $(docker ps -q --filter "ancestor=postgres:13")
 
       - name: Debug Postgres readiness
         if: failure()
